### ISSUE TITLE
How to remove the "Always open this in a container" icon from the Address/URL bar?

### ISSUE THREAD

**Issue by jimaldon** [mozilla/multi-account-containers#2066]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Steps to reproduce
1.
2.
3.

**Comment by unnamed777** [comment]
I'd like to do it too.

**Comment by whenov** [comment]
If you want to remove this button right now, add following code to your userChrome.css:
```css
#pageAction-urlbar-_testpilot-containers {
    display: none !important;
}
```
